# CONFIGURAÇÃO PARA TESTE LOCAL (EM CASA) - BANCO H2
spring.datasource.url=jdbc:h2:mem:argusdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# CRIA AS TABELAS AUTOMATICAMENTE NA MEMÓRIA RAM DO SEU PC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -------------------------------------------------------------
# CONFIGURAÇÃO DA FIAP (Mantenha comentada com '#' enquanto estiver em casa)
# spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
# spring.datasource.username=RMXXXXXX
# spring.datasource.password=sua_senha_aqui
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
